### ISSUE TITLE
Fatal error on new WordPress installation - " Class 'NV\Theme\Utilities\Theme' not found"

### ISSUE THREAD

**Issue by ViktorNova** [Veraxus/nouveau#6] opened 2016-03-15 08:09 UTC
I installed Nouveau on a fresh WordPress installation and instantly got a screen full of errors upon applying the theme:

````
Warning: call_user_func_array() expects parameter 1 to be a valid callback, class '\NV\Theme\Hooks\ThemeCustomize' not found in /home/wishostmain/public_html/_moanablu/wp-includes/plugin.php on line 525

Fatal error: Class 'NV\Theme\Utilities\Theme' not found in /home/wishostmain/public_html/_moanablu/wp-content/themes/nouveau-master/index.php on line 10
````

What is going on? I'm on PHP 5.4.45.    Thank you!

**Comment by Veraxus** [comment] 2016-03-16 05:10
The warning is fixed in 0.11.2 (just released).

I'm not sure what the Fatal error is about. I can't reproduce it at all.

**Closed by Veraxus** 2016-03-16 05:10 UTC
